### ISSUE TITLE
react-router - 'History' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by screendriver** [DefinitelyTyped/DefinitelyTyped#13299]
- [x] I tried using the latest `"@types/react-router@2.0.41` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react-router`.
  - The authors of that type definition are cc/ @RyanCavanaugh @sandersn @zhengbli @andy-ms 

I'm getting following errors:

`ERROR in /Users/me/Development/foo/node_modules/@types/react-router/lib/createMemoryHistory.d.ts
(3,57): error TS2694: Namespace '"/Users/me/Development/foo/node_modules/@types/react-router/lib/history"' has no exported member 'HistoryOptions'.`

`ERROR in /Users/me/Development/foo/node_modules/@types/react-router/lib/Router.d.ts
(113,64): error TS2702: 'History' only refers to a type, but is being used as a namespace here.`

My `tsconfig.json`:

```
{
  "compilerOptions": {
    "outDir": "www",
    "module": "es2015",
    "target": "es2015",
    "noImplicitAny": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react"
  }
}
```

My `package.json`:

```
{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "core-js": "^2.4.1",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-redux": "^4.4.6",
    "react-router": "^3.0.0",
    "redux": "^3.6.0",
    "whatwg-fetch": "^2.0.1"
  },
  "devDependencies": {
    "@types/react": "^0.14.55",
    "@types/react-dom": "^0.14.19",
    "@types/react-redux": "^4.4.35",
    "@types/react-router": "^2.0.41",
    "@types/redux": "^3.6.0",
    "@types/systemjs": "^0.19.32",
    "handlebars": "^4.0.6",
    "handlebars-loader": "^1.4.0",
    "html-webpack-plugin": "^2.24.1",
    "ts-loader": "^1.3.2",
    "tslint": "^4.0.2",
    "typescript": "^2.1.4",
    "webpack": "^2.1.0-beta.28"
  }
}
```

**Comment by andy-ms** [comment]
This could be solved by fixing #11514.
The problem is that you have "classic" module resolution, so the import of "history" in `react-router/lib/History.d.ts` refers to itself rather than to "@types/history". You could fix this by adding `"moduleResolution": "node"` to your tsconfig, or (preferably) by making a PR fixing the `react-router` definitions.

**Comment by rui-infotrack** [comment]
I've got the same problem here and this is my packages:

```
    "@types/history": "^2.0.31",
    "@types/react-router": "^2.0.44",
    "@types/react-router-redux": "^4.0.38",
    "history": "^2.1.2",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.7"
```
can anyone give some help here? thanks a lot!

**Comment by UlyssesInvictus** [comment]
It seems the history typings package just [changed their typings structure](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a1abf4fd44d411c689300f1c9fa99dc83e4de091) (as well as several other things, possibly, but I haven't looked too closely yet). They kept the other version around in a subfolder, and seem to have changed the configs for the dependent packages (react-router included) to use the right subfolder, but (I'm fairly new to TS, so this is more of a guess) I bet the build just hasn't been released yet. You might have to manually set the histories typing package version to something older in the meantime.

**Comment by dzharii** [comment]
@UlyssesInvictus thank you for noticing this: looks like @types/history was upgraded to v4.5.0 yesterday which made it incompatitable with react-router. 
I have installed the previous version: 

`npm i --save @types/history@2.0.45` 

and that solved my compilation issues

**Comment by donnyburnside** [comment]
@dzharii That worked for me, thanks!

**Comment by rui-infotrack** [comment]
@dzharii thanks, 2.0.45 resolved my problem!

**Comment by andy-ms** [comment]
`@types/history` version should be fixed as of the latest publish.

**Comment by yogesnsamy** [comment]
I'm encountering this issue still:

Current version:
```
  "@types/history": {
      "version": "4.7.8",
      "resolved": "https://registry.npmjs.org/@types/history/-/history-4.7.8.tgz",
      "integrity": "sha512-S78QIYirQcUoo6UJZx9CSP0O2ix9IaeAXwQi26Rhr/+mg7qqPy8TzaxHSUut7eGjL8WmLccT7/MXf304WjqHcA==",
      "dev": true
    },
```

After downgrading:
```
    "@types/history": {
      "version": "2.0.45",
      "resolved": "https://registry.npmjs.org/@types/history/-/history-2.0.45.tgz",
      "integrity": "sha1-x215pl0YkiDZ1Q9i4BQ72sMKVks="
    },
```

Error:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/28777569/130732418-4d32ec4e-356d-4a85-b67f-2f6984bb2f84.png">
