### ISSUE TITLE
Problem with connect() in @types/react-redux introduced in 4.4.41

### ISSUE THREAD

**Issue by forman** [DefinitelyTyped/DefinitelyTyped#16990]
Using `@types/react-redux` version 4.4.40, the following code

```typescript
import * as React from 'react';
import {connect} from "react-redux";

interface State {
    y: number;
}

// Own properties
interface OP {
    x: number;
}

// State properties
interface SP {
    y: number;
}

function mapStateToProps(state: State, ownProps: OP): OP & SP {
    return {
        x: ownProps.x,
        y: state.y,
    };
}

class TestComp extends React.Component<OP & SP, null> {
    render() {
        return <p>Hello</p>;
    }
}

export default connect(mapStateToProps)(TestComp);
```
would let me use `TestComp` as follows:

    const tc = <TestComp x={42}/>;

With version 4.4.41 and 4.4.42 the above leads to the following compilation error:

    error TS2324: Property 'y' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OP & SP, ComponentState>> & { children?:...'.

/cc  @thasner @seansfkelley @tkqubo @blakeembrey @sandersn  @mhegazy @andy-ms @hans-permana

**Comment by AndyBarron** [comment]
I'm getting this error as well. It feels like one of the typedefs accidentally swapped `TOwnProps` and `TMergedProps`/`TStateProps`, but I only took a cursory look at `index.d.ts`.

**Comment by brauliodiez** [comment]
Any update on this issue? I think it can be a showstopper for new developer coming to redux + typescript, thanks for you great work.

**Comment by sandersn** [comment]
@brauliodiez I merged @blakeembrey's fix. It should be available in an hour or so. Let me know if it helps.

**Comment by ritwik** [comment]
I think we're still seeing this issue even with the fixes from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16969. Here's a dummy component I made to try and isolate the issue:

```tsx

import * as React from "react"
import { connect, MapStateToProps, MapDispatchToPropsFunction } from "react-redux"


interface RootState {
  globalA: string
  globalB: number
}

interface DumbComponentProps {
  a: string
  b: number
  c?: number
}

const DumbComponent = (props: DumbComponentProps): JSX.Element => {
  return (
    <div>Something: {props.a} {props.b} {props.c}</div>
  )
}

type ConnectedStateProps = Pick<DumbComponentProps, "a" | "b">
type ConnectedOwnProps = Pick<DumbComponentProps, "c">

const mapStateToProps: MapStateToProps<ConnectedStateProps, ConnectedOwnProps> = (
    state: RootState): ConnectedStateProps => {
  return {
    a: state.globalA,
    b: state.globalB
  }
}

const SmartComponent = connect(
  mapStateToProps
)(DumbComponent)

export default SmartComponent
```

I then use SmartComponent somewhere and pass in c (note that a & b are supposed to come from the state).

```tsx
...
return (
  <SmartComponent c{2} />
)
```

The error I get is:
```
error TS2322: Type '{ c: 2; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DumbComponentProps, ComponentState>> & R...'.
  Type '{ c: 2; }' is not assignable to type 'Readonly<DumbComponentProps>'.
    Property 'a' is missing in type '{ c: 2; }'.
```

Inspecting the types in VS Code, I notice that it's picking up the wrong type for SmartComponent. It thinks it's `React.ComponentClass<DumbComponentProps>` ... but it should be `React.ComponentClass<Pick<DumbComponentProps, "c">>` (i.e, it should only accept OwnProps. This makes sense from the types, where ComponentDecorator is a function that returns a `ComponentClass<T>` (where `T extends TOwnProps`) ... so unfortunately I don't know why it's not mapping correctly.

Am I doing something obviously wrong here? Is there a way to get the compiler to show me step by step what it's inferring?

**Comment by Nasdan** [comment]
It looks like mapDistpachToProps is not optional now. Is it ok or is a bug?

**Comment by ritwik** [comment]
An update to my comment above, after digging around a little - I've created a test case that currently fails (but I believe shouldn't) and a fix to the typings that handles my case, but doesn't handle the case where it has to guess what the OwnProps are (e.g `connect()(DumbComponent)`). My changeset is here:
https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...ritwik:react-redux/fix-ownprop-inference
Would like to help with solving this but I'm hitting the limits of my knowledge with typescript. If anyone has thoughts on my test case or suggestions, would love to discuss those.

**Comment by ritwik** [comment]
Just closing the loop here - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17196 looks like it fixes this for our codebase.

**Comment by proProbe** [comment]
Was this solved? Im currently getting this problem in ^5.0.8 (`IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick ...`). The only difference is that I am using `types` instead of `interfaces`.

**Comment by andy-ms** [comment]
@proProbe Could you provide your `@types/react-redux`, `@types/react`, and `redux` versions, and a sample that reproduces the error?
Also CC package authors: @tkqubo @thasner @kenzierocks @clayne11 @tansongyang @nicholasboll

**Comment by proProbe** [comment]
Sorry for the late answer! I was working with a sample to reproduce it. I then suddenly realized that this has been fixed in @types/react-redux: "^5.0.8". Thanks though!

**Comment by DmytroLapshyn** [comment]
Still getting it with "^5.0.10" :(

```
"@types/react": "^15.6.4",
"redux": "3.7.2",
"@types/react-redux": "^5.0.10"

```

**Comment by Rovanion** [comment]
I was able to resolve this in my own code base by type-parameterizing connect on the type of the return value of mapStateToProps and what I wanted ownProps to be. Taken out of context if I want to call my product list with a list of product id's like:

```
<ProductList productIDs={productIDs} />
```

and have `mapStateToProps` to translate those id's into products to be shown in the list like:

```
const mapStateToProps = (state: RootState, ownProps: {productIDs: List<UUID>}) => {
  return { products: state.get('products').filter(
    (p: Product) => ownProps.productIDs.contains(p.uuid)) };
};
```

then I had to parameterize `connect` like:

```
const ProductList = connect<ProductListProps, void, {productIDs: List<UUID>}>(mapStateToProps)(ProductListComponent);
```

**Comment by ClassicDarkChocolate** [comment]
After some investigation. I found a simple solution. What you only have to do is to have "compilerOptions": { "strict": true } in your tsconfig.json if you're connecting a React.Component<,> component.

**Comment by thenormalsquid** [comment]
Typescript 2.8.x fixes this. Upgrade and give it a try.

**Comment by ethanneff** [comment]
Breaks again in Typescript 3.0.1. Hi Thien!

**Comment by mukuljainx** [comment]
Breaking with 3.2.2 too.

**Comment by RunningCoderLee** [comment]
Does this issue has any updates?

**Comment by themodernlife** [comment]
Broke for me with Typescript 3.2.2 as well.  However, annotating `connect` with `connect<Props>` seems to fix it.

**Comment by mralj** [comment]
I have same issue, even with annotating connect :/

**Comment by oladhari** [comment]
I have the same issue too, no update at all?

**Comment by Hyjaz** [comment]
Breaking with TypeScript 3.2.4 too.

**Comment by iamsellek** [comment]
To everyone having this issue, make sure you are importing your connected component properly. I switched an already-existing component to have a connect() function once it needed to access app state from redux. While doing this, I switched from exporting a stateless function to exporting my class component as default. When I didn't change how I was importing it in other files, this error popped up.

**Comment by Hyjaz** [comment]
@iamsellek, isn't just:

`Import ConnectedComponent from './container'`?

Is there a specific way of importing a connected component?

**Comment by Hyjaz** [comment]
It is working.

**Comment by Haaxor1689** [comment]
Is there any workaround to at least silence this error locally?

**Comment by TroySchmidt** [comment]
Definitely seems like there is a flip flop somewhere in the OwnProps versus StateProps.  I am seeing this issue where we have Redux connected component that has children.

**Comment by dcefram** [comment]
All I did to silence this issue is to use `<any>`:

```javascript
export default connect<any>(states, actions)(SomeComponent);
```

also works if you use compose:

```javascript
export default compose<any>(
  connect(states, actions),
  withStyles(styles)
)(SomeFunctionalComponent);
```

This should silence the error when passing props to the 'smart'/connected component.

**Comment by TroySchmidt** [comment]
Doesn't that also destroy all the type checking and Intellisense?  So what is the point of adding the typings at all then? @dcefram

**Comment by dcefram** [comment]
Yeah, it's a workaround just to silence the compiler and allow it to build to prevent this from being a "show stopper" (or in my case, to prevent me from re-writing everything away from TS or getting stalled until a fix is out). It's not **THE** solution though.

I too, am waiting for the fix for this :)

**Comment by Haaxor1689** [comment]
Better workaround is to manually type the `connect` call like this:

```ts
type StateProps = {
  // Attributes that you want mapped from redux store
}
type DispatchProps = {
  // Dispatch actions
}
type OwnProps = {
  // Other props that component expects when being created
}
type Props = StateProps & DispatchProps & OwnProps;
class ExampleComponent extends React.Component<Props> { /* ... */ }

const mapStateToProps = (state: State, ownProps: OwnProps): StateProps => { /* .. */ }
const mapDispatchToProps = (dispatch: Dispatch): DispatchProps => { /* ... *. }

export default connect<StateProps, DispatchProps, OwnProps>(mapStateToProps, mapDispatchToProps)(ExampleComponent)
```

This should create correct connected component that expects `OwnProps` when being created and no other state nor dispatch props.

**Comment by TroySchmidt** [comment]
Negative.  It still is trying to infer the types.  Instead I have to override manually type a `const` and then return that as the default.  

```
const connected: React.ComponentType<OwnProps> = connect<StateProps, DispatchProps, OwnProps>(......)(Component);
export default connected;
```

**Comment by bhanu499** [comment]
Facing the same issue with connect() using "@types/react-redux": "7.0.1" . No solutions mentioned seem to helped. @TroySchmidt  Can you share how you have used this "connected" in the parent component if possible some sample code would be very helpful

**Comment by Ringert** [comment]
Hi, I had a similar error. react-redux doesn't seem to resolve the return value of mapStateToProps as "TInjectedProps", which causes the wrong exclusion in the Omit helper **@types/react-redux index.d.ts:110** ``export type InferableComponentEnhancerWithProps``.

the definition of the type in the connect function solves the problem 

```typescript
// connect Redux
export const RCABBHeader = connect
<IABBHeaderStateToProps, //returned by mapStateToProps
 {}, // not necessary
 IABBHeaderProps, // props you want to pass through jsx/tsx
 IABBHeaderConnectedReduxStateProps, // combined from IABBHeaderMapStateToprops and IABBHeaderProps
 {}// not necessary
>(
    (state: IABBSettingState): IABBHeaderStateToProps => {
        return {
            headerLogoURL: state.settings.headerLogoURL
        }
    },
    undefined,
    undefined,
    { forwardRef: true }
)(ABBHeader);
```
```json
{
  "dependencies": {
    "react": "^16.8.6",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1"
  },
  "devDependencies": {
    "@types/react": "^16.8.17",
    "@types/react-redux": "^7.0.6",
    "react-scripts-ts": "^4.0.8",
    "typescript": "^3.4.5"
  }
}

```

**Comment by alexandrudanpop** [comment]
Is there any update for this?

**Comment by justemit** [comment]
Recently, I write a component which would `connect` to redux. When I use this component in other place, all the props of it are missing. And fix it by:

**Comment by justemit** [comment]
Recently, I write a component which would `connect` to redux. When I use this component in other place, all the props of it are missing. And fix it by:

```typescript
type StateProps = {
  /* some code */
};

type DispatchProps = {
  /* some code */
};

type OwnProps = {
  /* some code */
};

type Props = StateProps & DispatchProps & OwnProps;

const mapStateToProps = (state: IReduxState): StateProps => ({
  /* some code */
});

const mapDispatchToProps = (dispath: Dispatch<AnyAction>): DispatchProps => {
  /* some code */
};

const BaseComponent: React.FC<Props> = (props: Props) => {
  /* some code */
};

export const RegisterForm: React.ComponentType<OwnProps> = connect<
  StateProps,
  DispatchProps,
  OwnProps,
  IReduxState
>(
  mapStateToProps,
  mapDispatchToProps
)(BaseComponent);
```

dependencies are below:

```json
{
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1",
  },
  "devDependencies": {
    "@types/react": "^16.8.22",
    "@types/react-dom": "^16.8.4",
    "@types/react-redux": "^7.1.0",
    "@types/redux": "^3.6.0",
    "typescript": "^3.5.2"
  }
}
```

**Comment by alexandrudanpop** [comment]
adding all those types instead of having some basic type inference does not seem like a good solution to me...

**Comment by SomeoneWeird** [comment]
This still seems like an issue. Fairly certain the problem was introduced in version `7.0.2`, as I can install `7.0.1` and type inference works correctly.

**Comment by pixelgoo** [comment]
Works for me.
@justemit  posted correct approach that works on the last versions of react and redux.

**Comment by ogtfaber** [comment]
@justemit Thank you this drove me crazy 🙌

**Comment by kdmadej** [comment]
I think this issue is still alive and well in `@types/react-redux@^7.1.2`:
```ts
const propTypes = {
  foo: PropTypes.number.isRequired,
  bar: PropTypes.func.isRequired
};

// inferring the Props type
interface Props extends PropTypes.InferProps<typeof propTypes> {}
// although doing it explicitly also yields the same result
interface Props {
  foo: number,
  bar: (...args: any[]) => any
}

const Foo = (props : Props) => <></>

Foo.propTypes = propTypes;
/* Foo.defaultProps = {
  foo: 1,
  bar: () => {}
} //*/

const mapStateToProps = (state : any) => ({
  foo: 1
})
const mapDispatchToProps = {
  bar: () => {}
}
const Bar = connect(mapStateToProps, mapDispatchToProps)(Foo)

const Baz = () => <Bar /> // throws an error
```
```
Type '{}' is missing the following properties from type 'Readonly<Pick<Pick<Props, never>, never> & Pick<InferProps<{ foo: Validator<number>; bar: Validator<(...args: any[]) => any>; }>, "foo" | "bar">>': foo, bar
```
If I uncomment `defaultProps` it works fine, although I don't think I should be forced to define defaults for required values.

It seems to me like props set by `connect` are not omitted from the props required by the resulting component.

Doesn't help if I cast `connect` to set `OwnProps` explicitly, as well as the type of `Bar`:
```ts
const Bar : React.ComponentType<{}> =
  connect<any, any, {}, any>(mapStateToProps, mapDispatchToProps)(Foo)
```

**Comment by david-deepblocks** [comment]
Something that might help with inference (still some manual work tho) is doing something like this
Going off of @kdmadej example
```typescript

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;
type OwnProps = {
  a: string;
  b: number;
}

type Props = StateProps & DispatchProps & OwnProps;

const Foo = (props : Props) => <></>

const mapStateToProps = (state : any) => ({
  foo: 1
})

const mapDispatchToProps = {
  bar: () => {}
}

export default connect(mapStateToProps, mapDispatchToProps)(Foo)


// In another file
const Baz = () => <Bar /> <-- this should throw error expecting `a` and `b`
```

The problem that I'm facing however, is when I add `OwnProps` to the mix. Using `<Bar />` anywhere should throw an error because of missing props `a` and `b`, but it isn't, and it's really bugging me (no pun intended).

I got around this using this 

```typescript
const ConnectedBar: React.ComponentType<OwnProps> = connect(mapStateToProps, mapDispatchToProps)(Bar);
export default ConnectedBar;
```

or equivalently 

```typescript
export default connect(mapStateToProps, mapDispatchToProps)(Foo) as React.ComponentType<OwnProps>;
```

**Comment by kdmadej** [comment]
I've fixed my issues using `React.FC<Props>` to properly type the function component 😉 
Updated the [original post](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16990#issuecomment-537851898)

**Comment by catalinberta** [comment]
I fixed this by typing the connect method

From:
```
export default connect(mapStateToProps, mapDispatchToProps)(App);
```
To:
```
export default connect<MapStateToProps, {}, {}, RootState>(mapStateToProps, mapDispatchToProps)(App);
```

**Comment by popadi** [comment]
Any updates on this? As @alexandrudanpop said, adding all those types instead of having some basic type inference does not seem like a good solution. I'm using `7.2.1` and I still have the same issue.

**Comment by Cubelaster** [comment]
Also experiencing the same issue. 
Started breaking after npm update.
My fix is as follows:
`export default connect(mapStateToProps)(ConnectedIntlProvider) as unknown as ComponentType<unknown>;`

However, this way it works:
`export default connect<StateFromProps, null, OwnProps, ApplicationState>(mapStateToProps)(viewWithIntl);`

Using 
    "@types/react": "16.9.49",
    "@types/react-redux": "^7.1.9",
    "typescript": "^4.0.3"
    "redux": "^4.0.5",
{
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
  },
  "devDependencies": {
    "@types/react": "16.9.49"
    "@types/react-dom": "16.9.8",
    "@types/react-redux": "^7.1.9",
    "typescript": "^4.0.3"
  }
}

**Comment by danielrsantana** [comment]
Any updated on this subject ? I'm using the following versions:

package.json

```json
  "dependencies": {
     ...,
    "react": "~16.13.1",
    "react-dom": "~16.13.1",
    "react-redux": "~7.2.1"
  },
  "devDependencies": {
     ...,
    "@types/react-dom": "~16.9.8",
    "@types/react-redux": "~7.1.9",
    "typescript": "^4.0.3"
  },
```

I tried the suggestions made by @kdmadej but they didn't worked to me.

Tks in advance.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
