### ISSUE TITLE
TS2430 when using @types/request with typescript 2.4.0

### ISSUE THREAD

**Issue by huineng** [DefinitelyTyped/DefinitelyTyped#17171]
- [X ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

when using typescript 2.4.0 i get this error

```
ERROR in [at-loader] ./node_modules/@types/request/index.d.ts:66:15 
    TS2430: Interface 'DefaultUriUrlRequestApi<TRequest, TOptions, TUriUrlOptions>' incorrectly extends interface 'RequestAPI<TRequest, TOptions, TUriUrlOptions>'.
  Types of property 'defaults' are incompatible.
    Type '(options: TOptions) => DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type '{ (options: TOptions): RequestAPI<TRequest, TOptions, RequiredUriUrl>; (options: (UriOptions & TO...'.
      Type 'DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type 'RequestAPI<TRequest, TOptions, RequiredUriUrl>'.
        Types of property 'delete' are incompatible.
          Type '{ (uri: string, options?: TOptions, callback?: request.RequestCallback): TRequest; (uri: string, ...' is not assignable to type '{ (uri: string, options?: TOptions, callback?: request.RequestCallback): TRequest; (uri: string, ...'. Two different types with this name exist, but they are unrelated.
            Types of parameters 'options' and 'options' are incompatible.
              Type '(UriOptions & TOptions) | (UrlOptions & TOptions)' is not assignable to type 'OptionalUriUrl & TOptions'.
                Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl & TOptions'.
                  Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl'.
                    Types of property 'uri' are incompatible.
                      Type 'string | Url' is not assignable to type 'string'.
                        Type 'Url' is not assignable to type 'string'.
```

**Comment by anode7** [comment]
the same for me. Only solution today: `npm r -D @types/request`

**Comment by victorandree** [comment]
Seeing the same issue on 2.3.4. Seems like quite an easy fix. It would seem that the fix is to simply add `| Url` to the `OptionalUriUrl` interface in the [relevant file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request/index.d.ts#L134). 

```
interface OptionalUriUrl {
    uri?: string | Url;
    url?: string | Url;
}
```

This at least fixes it on my machine. Haven't tested <2.3.4 though.

**Comment by artemnikotin** [comment]
The same for me as well, I am using 2.3.4 TS version to keep it working.

**Comment by sureshgururajan** [comment]
+1

I'm using 

```javascript
{
"@types/node": "7.0.32",
"typescript": "^2.3.2",
"request": "2.60.0"
}
```

and removed a lot of unnecessary dependencies that were using types/node: 7.0.33 to resolve this issue.

**Comment by nicolashenry** [comment]
It seems that the fix has not been released yet.

**Comment by amarzavery** [comment]
When I upgraded the dependency to `"@types/request": "^0.0.45", the error went away. Previously the upper limit was 0.0.42. tsc version that I am using is 2.4.1.

**Comment by pedrogryzinsky** [comment]
This error disappeared after changing `"@types/request"` from `0.0.43` to `^0.0.45`, `"typescript"` from `2.3.2` to `^2.4.1` and `"@types/node"` from `7.0.31` to `^7.0.33`.

**Comment by lostintime** [comment]
@pedrogryzinsky doesn't work with `"@types/request" 0.0.45`, `"@types/node" ^8.0.7` and `"typescript" ^2.4.1`.

**Comment by dolanmiu** [comment]
This is breaking nearly **ALL** my projects because I use request and it's @types a **lot**!

**Comment by lbguilherme** [comment]
This has been fixed, this issue can be closed. Just update your dependencies!

**Comment by ggabriel96** [comment]
This is still happening to me. I don't know why I'm not being able to update the types to 0.0.45... I got Node at 8.1.2, npm at 5.0.3, TypeScript at 2.4.2 and request at 2.81.0. Any thoughts?

**Comment by nottoseethesun** [comment]
@ggabriel96 If you have not already, you could try removing your `yarn.lock` or `package-lock.json` and then do `yarn install`.   This worked for me.

**Comment by AskYous** [comment]
I just updated the package version: `sudo npm i @types/request@0.0.45`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
