### ISSUE TITLE
@types/react-router-dom@4.0.4 (latest) doesn't include latest commit. Typings are not compatible with typescript >=2.3

### ISSUE THREAD

**Issue by alerd** [DefinitelyTyped/DefinitelyTyped#17437]
This commit is not there with version 4.0.4 https://github.com/DefinitelyTyped/DefinitelyTyped/commit/ea9de8a518b01fa4257d367418e95a4ed2897717?diff=unified

I get issues

`ERROR in [at-loader] ./src/app/components/Header/index.tsx:9:11 
    TS2605: JSX element type 'Link' is not a constructor function for JSX elements.
  Types of property 'setState' are incompatible.
    Type '{ <K extends never>(f: (prevState: void, props: LinkProps) => Pick<void, K>, callback?: () => any...' is not assignable to type '{ <K extends never>(f: (prevState: {}, props: any) => Pick<{}, K>, callback?: () => any): void; <...'.
      Types of parameters 'f' and 'f' are incompatible.
        Types of parameters 'prevState' and 'prevState' are incompatible.
          Type 'void' is not assignable to type '{}'.

ERROR in [at-loader] ./src/app/components/Header/index.tsx:10:11 
    TS2605: JSX element type 'Link' is not a constructor function for JSX elements.
`

**Comment by Torhal** [comment]
Related to #17405.

**Comment by alerd** [comment]
Was fixed with 4.0.5.

Thanks!

**Comment by gavingregory** [comment]
+1 fixed in 4.0.5:
```
npm install -D @typings/react-router-dom@4.0.5
```

**Comment by basharov** [comment]
I am still seeing this with 4.0.5:

Error:(70, 22) TS2605:JSX element type 'Redirect' is not a constructor function for JSX elements.
  Types of property 'setState' are incompatible.
    Type '{ <K extends never>(f: (prevState: void, props: RedirectProps) => Pick<void, K>, callback?: (() =...' is not assignable to type '{ <K extends never>(f: (prevState: {}, props: any) => Pick<{}, K>, callback?: (() => any) | undef...'.
      Types of parameters 'f' and 'f' are incompatible.
        Type '(prevState: {}, props: any) => Pick<{}, any>' is not assignable to type '(prevState: void, props: RedirectProps) => Pick<void, any>'.
          Types of parameters 'prevState' and 'prevState' are incompatible.
            Type 'void' is not assignable to type '{}'.

**Comment by szebrowski** [comment]
I also have a problem with Typescript 2.4:
`Error:(20, 16) TS2322: Type '{ path: "/:id"; component: ({ match }: { match: any; }) => Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Route<RouteProps>> & Readonly<{ children?: ReactNo...'.
  Type '{ path: "/:id"; component: ({ match }: { match: any; }) => Element; }' is not assignable to type 'Readonly<RouteProps>'.
    Types of property 'component' are incompatible.
      Type '({ match }: { match: any; }) => Element' is not assignable to type 'ComponentClass<{} | RouteComponentProps<any>> | StatelessComponent<{} | RouteComponentProps<any>>...'.
        Type '({ match }: { match: any; }) => Element' is not assignable to type 'StatelessComponent<{} | RouteComponentProps<any>>'.
          Types of parameters '__0' and 'props' are incompatible.
            Type '{ children?: ReactNode; } | (RouteComponentProps<any> & { children?: ReactNode; })' is not assignable to type '{ match: any; }'.
              Type '{ children?: ReactNode; }' is not assignable to type '{ match: any; }'.
                Property 'match' is missing in type '{ children?: ReactNode; }'.`

**Comment by szebrowski** [comment]
this should probably be closed?

**Comment by lucasljj** [comment]
Yep, just close this and delete react-router from this the repository, this typings just break everything

**Comment by iplus26** [comment]
Is this issue fixed? I've tried different versions of this definition and am still seeing `TS2605:JSX element type 'Redirect/Route/BrowserRouter' is not a constructor function for JSX elements.`

Remove `@types/react-router-dom` works for me....

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
