### ISSUE TITLE
@types/react-redux: Inferred wrong type in `connect` when component props is optional

### ISSUE THREAD

**Issue by MichalLytek** [DefinitelyTyped/DefinitelyTyped#19989]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Mentioning @blakeembrey, @andy-ms, @alecmerdler 😉 

Code:
```ts
import React, { Component } from "react";
import { connect } from "react-redux";

import { RootState } from "@src/state/state";

interface Props {
    normal: string;
    optional?: number;
}
class TestComponent extends Component<Props> {
    render() {
        return <h1>Hello</h1>;
    };
}
function mapStateToProps(_state: RootState) {
    return { 
        normal: "test",
        optional: 5,
    };
}
const Connected = connect(mapStateToProps)(TestComponent);
```
Error:
```
[ts]
Argument of type 'typeof TestComponent' is not assignable to parameter of type 'ComponentType<{ normal: string; optional: number | undefined; } & DispatchProp<any>>'.
  Type 'typeof TestComponent' is not assignable to type 'StatelessComponent<{ normal: string; optional: number | undefined; } & DispatchProp<any>>'.
    Type 'typeof TestComponent' provides no match for the signature '(props: { normal: string; optional: number | undefined; } & DispatchProp<any> & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.
```
The problem is when the `optional` prop is marked as optional - the `TestComponent` part of `connect(mapStateToProps)(TestComponent);` is reported red with above error code.

For unknown reasons the inferred type is `StatelessComponent` but `TestComponent` is a class.
When the prop is marked as `optional: number|undefined` all is ok, so it's a workaround for now.

**Comment by 19majkel94** [comment]
The workaround doesn't work when we use 3rd party HOC, like redux-form, which has some props optional, like `initialValues?: Partial<FormData>;`:

Code to reproduce:
```ts
interface State {
    stateString: string;
}

interface CompProps {
    propString: string;
}
interface FormData {
    name: string;
    age: number;
}
class TestComponent extends Component<CompProps& InjectedFormProps<FormData, CompProps>> {}

export const Form = reduxForm<FormData, CompProps>({
    form: "test",
    destroyOnUnmount: true,
})(TestComponent);

export const Connected = connect(
    (state: State) => ({
        propString: state.stateString,
        initialValues: { name: "", age: 23 },
    }),
)(Form);
```
I got this not meaningful error:
```
Argument of type 'DecoratedComponentClass<FormData, CompProps & Partial<ConfigProps<FormData, CompProps>>>' is not assignable to parameter of type 'ComponentType<{ propString: string; initialValues: { name: string; age: number; }; } & DispatchPr...'.
  Type 'DecoratedComponentClass<FormData, CompProps & Partial<ConfigProps<FormData, CompProps>>>' is not assignable to type 'StatelessComponent<{ propString: string; initialValues: { name: string; age: number; }; } & Dispa...'.
    Type 'DecoratedComponentClass<FormData, CompProps & Partial<ConfigProps<FormData, CompProps>>>' provides no match for the signature '(props: { propString: string; initialValues: { name: string; age: number; }; } & DispatchProp<any> & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.
```
In connect I can specify only non optional and not undefined props, like "form". Even marking as required and with undefined union doesn't work in this case.

The pick props from redux-form config works ok, if I doesn't provide `form` name in redux-form, I had to to this in connect or in JSX `<Form form="test" />`.

**Comment by 19majkel94** [comment]
Ping authors after 2 weeks 😉 
 @tkqubo @thasner @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo

**Comment by rafeememon** [comment]
I believe this may have been fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21730.  I needed to make additional changes in my project to account for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21400 but after upgrading to v5.0.14 everything seems happy again.

**Comment by 19majkel94** [comment]
@rafeememon 
Unfortunately not 😞 I've installed `5.0.14` and the error is still here:
![image](https://user-images.githubusercontent.com/10618781/33396755-cf341a98-d549-11e7-8a12-e81afd833131.png)
![image](https://user-images.githubusercontent.com/10618781/33396831-0cd06474-d54a-11e7-88f6-4acd1c9a2750.png)
The problem is that `connect` types perform the type check from inverse side, so not optional type `a: A|undefined` is not assignable to `a:? A`.

**Comment by simast** [comment]
Mentioning all authors for any help: @tkqubo, @thasner, @kenzierocks, @clayne11, @tansongyang, @nicholasboll, @mdibyo, @pdeva

There still seems to be issues with optional props as described by @19majkel94 one comment above. I am seeing similar behaviour when I use a simple HOC. I was able to reproduce this in a test case:

```typescript
namespace MapStateOptionalPropHOC {
    
    const hideableHOC = <TProps extends {}>(
        Component: React.ComponentType<TProps>
    ): React.StatelessComponent<TProps & {hidden: boolean}> => (
        props
    ) => (
        props.hidden ? null : <Component { ...props } />
    )

    interface OwnProps {}
    interface StateProps { bar?: number }
    interface DispatchProps { dispatch?: Dispatch<any> }

    class TestComponent extends Component<OwnProps & StateProps & DispatchProps> {}

    const mapStateToProps = (_: any) => ({
        bar: 1,
        hidden: false
    })

    const Test = connect(
        mapStateToProps
    )(hideableHOC(TestComponent))

    const verify = <Test />
}
```

This fails with:

`[ts] Argument of type 'StatelessComponent<OwnProps & StateProps & DispatchProps & { hidden: boolean; }>' is not assignable to parameter of type 'ComponentType<{ bar: number; hidden: boolean; } & DispatchProp<any>>'.`

on **types/react-redux** 5.0.14 and **typescript** 2.6.2. Any suggestions what might be the issue?

**Comment by 19majkel94** [comment]
> Any suggestions what might be the issue?
Yes, the problem is with HOC - they behave like function that accept an argument (a component). So `connect` infer the `props` type from `mapStateToProps` function and the compiler check if the component props match the connect props. So it failed because `bar` is `number` so `Props` with optional `bar` is not assignable.

The solution is to have interfaces for `mapStateToProps` props type to disable the inferring of not optional type.

**Comment by danizord** [comment]
Having the same issue here :/
Fun fact: it works normally with functional components, but not with class components.

**Comment by DanHarman** [comment]
I hit this. You can fix easily enough with a cast.

```
function mapStateToProps(_state: RootState) {
    return { 
        normal: "test",
        optional: 5,
    } as Partial<Props>;
}
```

At least it works for me.

**Comment by nwinger** [comment]
@DanHarman `Partial<Props>` - Props coming from where?

**Comment by DanHarman** [comment]
@nwinger My suggestion was if you had code as per the original in the first post.

**Comment by mDibyo** [comment]
@19majkel94 Could you try this? (Adapted the example from the initial post in this issue)
```
import React, { Component } from "react";
import { connect } from "react-redux";

import { RootState } from "@src/state/state";

interface Props {
    normal: string;
    optional?: number;
}
class TestComponent extends Component<Props> {
    render() {
        return <h1>Hello</h1>;
    };
}
function mapStateToProps(_state: RootState) {
    return { 
        normal: "test",
        optional: 5,
    };
}
const Connected = connect<Props>(mapStateToProps)(TestComponent);
```

**Comment by 19majkel94** [comment]
What about `mapDispatchToProps` and `OwnProps`? I had to create 3 interfaces and the union type to merge them together in `Props`. I know it works, the issue is about inferencing from shape of connect parameters and it can't be done for now as it's how TS works with HOC 😕

**Comment by mDibyo** [comment]
@19majkel94 Just read the rest of the discussion above thoroughly. Sorry for bringing up something that has already been discussed.

And I understand your concern with having to define the extra interfaces/types. Quite often, more than half of my component file is spent on that boilerplate.

**Comment by aappddeevv** [comment]
If you have any "own props" then you need to define that shape and ensure they are on the mapping functions (if they take the own props as the 2nd parameter). Then connect will and inference will happen *if* you also define your component/function to take the "own props" & "the props from the mapping functions or you can just put a plug in in". The bottom line I think is that if you have any props coming from the "parent owner" and not just he redux store, you need to define the own props structure and ensure your component takes ownprops and the "rest of your props." To be totally typesafe, you need to define all three types and & them together in your component.

**Comment by BetterCallSky** [comment]
@DanHarman 

Casting to `Partial<Props>` can be error-prone. If you forget to provide a required prop, typescript won't report such error.

It works fine if we cast it to a stateless component.
```ts
connect(mapStateToProps, mapDispatch)(MyComponent as any as React.SFC<Props>)
```

Or we can use conditional types to create an util for converting to SFC. It's a better solution if we don't have `Props` definition.


```ts
type ToSFC<T> = T extends React.ComponentClass<infer Props> ? React.SFC<Props> : T;

function toSFC<T>(component: T) {
  return component as ToSFC<T>;
}

connect(mapStateToProps, mapDispatch)(toSFC(MyComponent))
```

**Comment by Bosn** [comment]
Have the same issue, seems the best way current solution is using 
```typescript
connect(mapStateToProps, mapDispatch)(MyComponent as any)
```

**Comment by sargunv** [comment]
I had this issue. The problem was the return type of my `mapStateToProps` functions didn't have the same optionals the original `Props` type did. I fixed it by using `Pick` in the following way, pulled from my code based on the Typescript React tutorial:

```
export function mapStateToProps({ enthusiasmLevel, languageName }: StoreState) {
  let props = {
    enthusiasmLevel,
    name: languageName
  }
  return props as Pick<Props, keyof typeof props> // this is the key line
}
```

Here's my full example:
```
interface Props {
  name: string // this comes from redux state
  enthusiasmLevel?: number // this comes from redux state
  onIncrement?: () => any // this comes from redux dispatch
  onDecrement?: () => any // this comes from redux dispatch
  greeting: string // this is passed through the container component
}

class Hello extends React.Component<Props> {
  render() {
    return ( /* snipped for brevity */ )
  }
}

function mapStateToProps({ enthusiasmLevel, languageName }: MyState) {
  let props = {
    enthusiasmLevel,
    name: languageName
  }
  return props as Pick<Props, keyof typeof props>
}

function mapDispatchToProps(dispatch: Dispatch<actions.EnthusiasmAction>) {
  let props = {
    onIncrement: () => dispatch(actions.incrementEnthusiasm()),
    onDecrement: () => dispatch(actions.decrementEnthusiasm())
  }
  return props as Pick<Props, keyof typeof props>
}

export default connect(mapStateToProps, mapDispatchToProps)(Hello)
```

**Comment by Bosn** [comment]
After sometime of search, this is the best solution doc of TypeScript + React:

[https://github.com/piotrwitek/react-redux-typescript-guide](https://github.com/piotrwitek/react-redux-typescript-guide)
### Example: SFC
```typescript
import * as React from 'react'
import { formatSex, formatDocState, formatGoal, formatPriority } from '@app/state/ducks/crm/doc/types'
import TableRow from '@material-ui/core/TableRow'
import TableCell from '@material-ui/core/TableCell'
import Hidden from '@material-ui/core/Hidden'
import { RouteComponentProps, withRouter } from 'react-router-dom'
import { Theme, withStyles, WithStyles } from '@material-ui/core/styles'
import config from '@app/../config'

const V = config.VERSION

const styles = (theme: Theme) => ({
  row: {
    '&:nth-of-type(odd)': {
      backgroundColor: theme.palette.background.default,
    },
  },
})

export interface DocListItemViewProps extends RouteComponentProps<{}> {
  id: number
  name: string
  sex: number
  priority: number
  dealPossibility: number
  mobile: string
  docState: number
  goal: number
}

type PropsWithStyles = DocListItemViewProps & WithStyles<'row'>

const DocListItem: React.SFC<PropsWithStyles> = (props) => {
  const { id, name, priority, dealPossibility, mobile, sex, docState, goal, classes } = props
  return (
    <TableRow
      onClick={() => {
        props.history.push(`/${V}/crm/doc/updateDoc/${id}`)
      }}
      className={classes.row}
    >
      <Hidden mdDown={true}>
        <TableCell>{id}</TableCell>
      </Hidden>
      <TableCell>{name}</TableCell>
      <Hidden xsDown={true}>
        <TableCell>{formatSex(sex)}</TableCell>
      </Hidden>
      <TableCell>{formatPriority(priority)}</TableCell>
      <Hidden xsDown={true}>
        <TableCell>{formatDocState(docState)}</TableCell>
      </Hidden>
      <Hidden smDown={true}>
        <TableCell>{dealPossibility}</TableCell>
      </Hidden>
      <Hidden lgDown={true}>
        <TableCell>{formatGoal(goal)}%</TableCell>
      </Hidden>
      <TableCell>{mobile}</TableCell>
    </TableRow>
  )
}
export default withRouter(withStyles(styles)(DocListItem))
```

### Example of React + Redux + Material UI + Webpack4 Hot reloading
```typescript
import * as React from 'react'
import CRMLayout from '@app/views/layout/CRMLayout'
import { withStyles, WithStyles } from '@material-ui/core/styles'
import { hot } from 'react-hot-loader'
import { connect } from 'react-redux'
import { RootState } from 'src/app/state/rootReducer'
import * as SharedActions from '@app/state/ducks/shared/actions'
import { BOTTOM_NAVIGATION_ITEM_TYPE } from '@app/state/ducks/shared/types'
import Avatar from '@material-ui/core/Avatar'
import Paper from '@material-ui/core/Paper'
import * as classnames from 'classnames'
import DataSummaryItem from '@app/views/components/common/DataSummaryItem'
import NameSummaryItem from '@app/views/components/common/NameSummaryItem'
import ScheduleList from '@app/views/components/common/ScheduleList'
import ActivityList from '@app/views/components/common/ActivityList'

const decorator = withStyles(({ spacing }) => ({
  container: {
  },
  block: {
    marginBottom: spacing.unit,
    padding: spacing.unit * 2,
  },
  summary: {
    display: 'flex',
    flexDirection: 'row' as 'row',
  },
  schedules: {
  },
  activities: {
  },
  avatar: {
    width: 60,
    height: 60,
  },
}))

interface CRMIndexProps {
  switchBottomNavigation: (item: BOTTOM_NAVIGATION_ITEM_TYPE) => any
}

interface CRMIndexStates {
}

type PropsWithStyles = CRMIndexProps & WithStyles<'container' | 'block' | 'summary' | 'schedules' | 'activities' | 'avatar'>

const CRMIndex = decorator(
  class extends React.Component<PropsWithStyles, CRMIndexStates> {

    componentDidMount() {
      this.props.switchBottomNavigation(BOTTOM_NAVIGATION_ITEM_TYPE.CRM_INDEX)
    }

    render() {
      const { classes } = this.props
      return (
        <CRMLayout>
          <div className={classes.container}>
            <Paper square={true} className={classnames(classes.summary, classes.block)}>
              <Avatar
                src="https://cdn.bolifestudio.com/public/uploads/1_2_avatar_1522051846699?x-oss-process=image/resize,w_128"
                className={classes.avatar}
              />
              <NameSummaryItem name="马圣博 Bosn" title="行政秘书" />
              <DataSummaryItem label="提成" value="￥6,400" />
              <DataSummaryItem label="销售" value="￥80,000" />
            </Paper>
            <Paper square={true} className={classnames(classes.schedules, classes.block)}>
              <ScheduleList />
            </Paper>
            <Paper square={true} className={classnames(classes.activities, classes.block)}>
              <ActivityList />
            </Paper>
          </div>
        </CRMLayout>
      )
    }

  }
)

const mapStateToProps = (_state: RootState) => {
  return {
  }
}

const mapDispatchToProps = ({
  switchBottomNavigation: SharedActions.switchBottomNavigation,
})

export default connect(mapStateToProps, mapDispatchToProps)(hot(module)(CRMIndex))
```

**Comment by sargunv** [comment]
@Bosn If I'm reading it correctly, I believe your second example would not compile if `switchBottomNavigation` was optional in `interface CRMIndexProps`, which is the issue in this thread. @BetterCallSky's `React.SFC` example solves that issue, but then causes errors with pass through props (ones that are not mapped from state or dispatch). I'll have to work with it a bit longer to be 100% sure, but I believe that using `Pick` in the mapping functions (as in my example above) cleanly solves both issues while maintaining type inference in `connect`.

**Comment by Bosn** [comment]
@sargunv I think this issue had been fixed, I use the newest version packages, and try to rebuild the error, but it compiles successfully. My code:

```typescript
import * as React from 'react'
import { connect } from 'react-redux'
import { RootState } from 'src/app/state/rootReducer'

export interface DocListViewProps {
  optional?: number
}
export interface DocListViewStates {
}


class SalesAnalyze extends React.Component<DocListViewProps, DocListViewStates> {
  render() {
    const { optional } = this.props
    return (
      <div>
        sales charts page{optional}
      </div>
    )
  }
}

const mapStateToProps = (_state: RootState) => {
  return {
  }
}

const mapDispatchToProps = ({
})

export default connect(mapStateToProps, mapDispatchToProps)(SalesAnalyze)
```

**Comment by sargunv** [comment]
@Bosn You need to populate the optional prop in `mapStatesToProps` to reproduce the error.

**Comment by Bosn** [comment]
@sargunv The example given by the issue author can be compiled successfully via TypeScript 2.9.0 (Using VSCode Insider, at right/bottom corner, choose 2.9.0-insiders.20180510

For older versions, this can be fixed by just adding function returning type of `mapStateToProps` as `Props`, this is the full example.

```typescript
import * as React from 'react'
import { connect } from 'react-redux'

interface RootState {
}

interface Props {
    normal: string
    optional?: number
}
class TestComponent extends React.Component<Props> {
    render() {
        return <h1>Hello</h1>
    }
}
function mapStateToProps(_state: RootState): Props {  // here, I add the type to match, or use new derived interface.
    return {
        normal: 'test',
        optional: 5,
    }
}
const Connected = connect(mapStateToProps)(TestComponent)

export default Connected

```

**Comment by Bosn** [comment]
For convenience, also can use Partial<Props> as the returning type of `mapStateToProps`. For strictly use, I think it'd be better to define myself to match the interface below:

```typescript
interface MapProps {
    normal: string
    optional?: number
}

function mapStateToProps(_state: RootState): MapProps { 
    return {
        normal: 'test',
        optional: 5,
    }
}

```

**Comment by sargunv** [comment]
@Bosn That's exactly what the `Pick` solution is doing, except without duplicating the prop definitions.

These two code blocks are essentially equivalent, but the second avoids defining the `normal` and `optional` props twice.

```
interface Props {
  normal: string
  optional?: number
  other: string
}

interface MapProps {
    normal: string
    optional?: number
}

function mapStateToProps(_state: RootState): MapProps { 
  return {
    normal: 'test',
    optional: 5,
  }
}
```

```
interface Props {
  normal: string
  optional?: number
  other: string
}

function mapStateToProps(_state: RootState) { 
  let props = {
    normal: 'test',
    optional: 5,
  } as Pick<Props, keyof typeof props>
  return props
}
```

**Comment by Bosn** [comment]
@sargunv Your solution is shorter, but can't be right. You can see my example, when property `normal` is *REQUIRED*,  for your method, all properties will be *OPTIONAL*.

```typescript
import * as React from 'react'
import { connect } from 'react-redux'

interface RootState {
}

interface Props {
    normal: string
    optional?: number
    other: string
}
class TestComponent extends React.Component<Props> {
    render() {
        return <h1>Hello</h1>
    }
}
function mapStateToProps(_state: RootState) {
    const props =  {
        other: 'haha',  // property normal required !!! But no compile error~
    }
    return props as Pick<Props, keyof typeof props>
}
const Connected = connect(mapStateToProps)(TestComponent)

export default Connected

```

**Comment by shudson250** [comment]
Posting this here for feedback to this issue...

I hate declaring all Redux props as optional, so I opt to create two interfaces; Props & ReduxProps. That way when I implement the component, I don't get any extraneous properties showing (the optional redux-connect props). Problem is, when I use connect() I get a ts error that says 
```
Argument of type 'typeof TestComponent' is not assignable to parameter of type 'ComponentType<never>'.
  Type 'typeof TestComponent' is not assignable to type 'ComponentClass<never, any>'.
    Types of property 'defaultProps' are incompatible.
      Type 'Partial<Props>' is not assignable to type 'never'.
```

In order to fix that issue and get sane code completion, I have resorted to casting the components. Here's what I've done, written as the TestComponent:

```
import * as React from 'react'
import { connect } from 'react-redux'

interface Props {
  normal: string
  optional?: number
  other: string
}

interface ReduxProps {
  isAuthenticated: boolean;
  username: string;
}
class TestComponent extends React.Component<Props & ReduxProps> {
  constructor(props: Props & ReduxProps) {
    super(props);
  }
  render() {
      return <h1>Hello{this.props.isAuthenticated ? ` ${this.props.username}` : ''}</h1>
  }
}
const mapState = state => ({
  isAuthenticated: state.auth.isAuthenticated,
  username: state.auth.username,
});

// To prevent TS from throwing error output as above, cast the final component just with Props
// and cast the connect-input component with all props
// const Connected = connect(mapStateToProps)(TestComponent)
const Connected = connect(
  mapStateToProps
)(
 TestComponent as React.ComponentClass<Props & ReduxProps>
) as React.ComponentClass<Props>;

export default Connected
```

Now code completion will only show `normal, other, optional?`

I hate having to do the extra casting so if you have suggestions on why this is necessary please fire away.

**Comment by PierreGUI** [comment]
Any clue how to fix this at the source?
In [index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts) I'll have a look around the `Omit` of `InferableComponentEnhancerWithProps`...

Any hint is welcome :')

**Comment by AlexReff** [comment]
This is still an issue, a year later. Is there anyone that can identify and fix this issue?

**Comment by junalmeida** [comment]
@DylanVann I saw that you commited recently on this project, would you mind to take a look on this, or redirect to someone who can? Thx

**Comment by DylanVann** [comment]
I'd try using the hooks API instead of using `connect`. Typing HOCs is too painful.

**Comment by junalmeida** [comment]
@DylanVann I far as I can see, hooks api works for function components, we are using class components.

**Comment by junalmeida** [comment]
For all participants in this thread, if you use `yarn` (I'm not sure about `npm`), please refer the typings version on `resolutions` node of `package.json`.

These are my versions: 
```
"resolutions": {
        "@types/react": "16.9.11",
        "@types/prop-types": "15.7.3",
        "@types/react-dom": "16.9.4",
        "@types/react-redux": "7.1.5"
    },
```
After this change some incompatible type errors are gone.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by parnekov** [comment]
I had an optional field in return mapStateToProps but had NOT optional same field in component props
