### ISSUE TITLE
react-native wrong types for AsyncStorageStatic

### ISSUE THREAD

**Issue by JLarky** [DefinitelyTyped/DefinitelyTyped#24250]
- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @timwangdev @kamal @nelyousfi

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L6472
```
    getItem(key: string, callback?: (error?: Error, result?: string) => void): Promise<string>;
```

So far it looks like type for value is `string | null` (like for localStorage) in [docs](https://facebook.github.io/react-native/docs/asyncstorage.html#getitem) they show it as `?string` (whatever that means in Flow), but definition has `result?: string` and `Promise<string>` which are not true.

**Comment by alloy** [comment]
`?string` means `string | null` indeed. From the docs it’s unclear to me what type the resulting Promise does yield, am I overlooking it?

Will you be submitting a PR for this?

**Comment by JLarky** [comment]
@alloy I just started with react native :) so I don't know all the types yet, but this is the code that I used
```tsx
AsyncStorage.getItem("some_value").then(
    (text: string | null) => {
        console.log(text);
    },
    err => {
        console.error(err);
    }
```

and so far it did return the `null`, not `undefined`

as for PR, I wish someone who works more often with that than me does it :)

**Comment by alloy** [comment]
Yeah it looks like the value would either be `string` or `null` indeed https://github.com/facebook/react-native/blob/8466db0fd355aea778ff71cfb10c927cfd18a551/Libraries/Storage/AsyncStorage.js#L45

We (the RN typings maintainers) don’t generally take ‘request’ tickets, as it always ends up taking more time than we’d want. You’re welcome to let it sit for now, but I can’t promise when/if anybody else picks this up.

**Comment by alloy** [comment]
Closing as it’s probably fixed by #28052

**Comment by JLarky** [comment]
@alloy it was only partially fixed. `result?: string` is still wrong and should be `result: string | null`. I see this kind of error all the time in typescript definitions, for some reason people think that if you are not using argument you have to make it optional :) same goes for `error?: Error` why this argument is optional?

**Comment by alloy** [comment]
Ah yes, that’s correct. My bad, I just went off [this comment](
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28052#issuecomment-412350449). Can you please either comment on that PR instead or provide a PR that finishes it?
