### ISSUE TITLE
Duplicate identifier with @types/node 10.0

### ISSUE THREAD

**Issue by rbirkgit** [DefinitelyTyped/DefinitelyTyped#25342]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @.types/node 10.0

With v9.6.6 everything was fine with my Angular project. Upgraded to 10.0.0 and now I get the following errors running my unit tests:

`
Error: node_modules/@types/node/index.d.ts(2381,15): error TS2300: Duplicate identifier 'URL'.
node_modules/@types/node/index.d.ts(2399,15): error TS2300: Duplicate identifier 'URLSearchParams'.
node_modules/@types/node/index.d.ts(2417,14): error TS2661: Cannot export 'URL'. Only local declarations can be exported from a module.
node_modules/@types/node/index.d.ts(2417,19): error TS2661: Cannot export 'URLSearchParams'. Only local declarations can be exported from a module.
node_modules/typescript/lib/lib.dom.d.ts(12210,11): error TS2300: Duplicate identifier 'URL'.
node_modules/typescript/lib/lib.dom.d.ts(12226,13): error TS2300: Duplicate identifier 'URL'.
node_modules/typescript/lib/lib.dom.d.ts(14282,11): error TS2300: Duplicate identifier 'URLSearchParams'.
node_modules/typescript/lib/lib.dom.d.ts(14309,13): error TS2300: Duplicate identifier 'URLSearchParams'.
`

**Comment by westy92** [comment]
I was just about to log this same issue!

I tried this:
```
npm init
npm i -g typescript
npm i --save-dev @types/node
tsc --init
touch index.ts
tsc
```

I get these same errors.

**Comment by westy92** [comment]
Adding additional mention for the latest author: @rbuckton.

**Comment by allada** [comment]
I am also seeing this. The last push broke our build with this same error.

**Comment by elarbee** [comment]
Also getting this. Looks like a conflict with Typescript.

**Comment by westy92** [comment]
Yes. In the OP's post, the conflict is with `lib.dom.d.ts`. I also see conflits with `lib.d.ts` and `lib.es2017.full.d.ts`.

**Comment by pshihn** [comment]
yep. seeing this as well.

**Comment by westy92** [comment]
We're still using the latest LTS (8), so we solved this (for now) by using `^8.0.0`.

**Comment by rbuckton** [comment]
I will be able to look at this tonight.

**Comment by styfle** [comment]
You can get an idea of the impact of this breaking change with @dependabot [![Dependabot compatibility score](https://api.dependabot.com/badges/ci_status?dependency-name=@types/node&package-manager=npm_and_yarn&previous-version=9.6.6&new-version=10.0.0)](https://dependabot.com/compatibility-score.html?dependency-name=@types/node&package-manager=npm_and_yarn&previous-version=9.6.6&new-version=10.0.0)
Probably most TS users are including `@types/node` which is causing the duplicate identifier and [failing CI](https://travis-ci.org/styfle/packagephobia/builds/371875198).

@rbuckton Thanks for looking into this 👍

**Comment by jantimon** [comment]
Quick fix:

```
npm i @types/node@8.0.0
```

**Comment by abramenal** [comment]
For old-fashioned guys with nodejs v6.x.x - `@types/node@6`

**Comment by robertbradleyux** [comment]
This was broken because these classes were changed to be globally exported, line 2380 in the current file. See the history comparison below:

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/bffb03282272b37ccb12429026f4504a39a3cd83#diff-7d84e08967cded0b99ed4328aab0a1a8

**Comment by styfle** [comment]
@robertbradleyux In node 10.0.0, [The URL class is also available on the global object](https://nodejs.org/dist/latest-v10.x/docs/api/url.html#url_class_url) so this seems correct.

@rbuckton Is there a way to tell typescript to only define the class if it is not already defined?

In this case, both node and the browser implement the same WHATWG URL Standard so there must be a way to converge the two typings, right?

**Comment by kgorlick** [comment]
After clearing my npm cache I am still getting the original error

**Comment by rbuckton** [comment]
@kgorlick This won't show up until the types publisher publishes the updated types to npm.

**Comment by rbuckton** [comment]
@styfle, NodeJS and DOM have slight differences in their implementations of the WHATWG URL standard (e.g. the NodeJS version has a `toJSON()` that isn't in the DOM version, and the DOM version has a static `createObjectURL` method that does not appear in the NodeJS version).

**Comment by ohrrkan** [comment]
I temporary fix the issue adding     
"lib": ["es6"],
in my tsconfig.json

**Comment by styfle** [comment]
@rbuckton I understand their might be some differences in the `URL` definitions.

`setTimeout` has a different return type in Node.js than the browser: [docs](https://nodejs.org/dist/latest-v10.x/docs/api/timers.html)

Yet somehow, including `@types/node` doesn't break the build. How does that one work?

**Comment by rbuckton** [comment]
IIRC, the multiple versions of the timer APIs become overloads. The problem with URL is that it is an object type.

**Comment by luckyyang** [comment]
Got this error on `@11.9.3` and fixed by:
`npm i @types/node@10.5.7 --save-dev`

**Comment by Mulperi** [comment]
Getting this error 
with "@types/node": "^11.9.4",



node_modules/@types/node/index.d.ts:75:15 - error TS2300: Duplicate identifier 'SharedArrayBuffer'.

75 declare class SharedArrayBuffer {
                 ~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts:24:11
    24 interface SharedArrayBuffer {
                 ~~~~~~~~~~~~~~~~~
    'SharedArrayBuffer' was also declared here.
  node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts:46:13
    46 declare var SharedArrayBuffer: SharedArrayBufferConstructor;
                   ~~~~~~~~~~~~~~~~~
    and here.

node_modules/@types/node/index.d.ts:83:15 - error TS2451: Cannot redeclare block-scoped variable 'custom'.



etc.....

**Comment by Flarna** [comment]
@Mulperi I think your issue is different to the above and related to the change of `interface SharedArrayBuffer` to `class SharedArrayBuffer` done in #32878.

@SimonSchick I think this should be changed back as it is actually just a forward declaration.

**Comment by SimonSchick** [comment]
@Flarna this will only work if you load dom typings tho, node typings should work without loading dom typings..

**Comment by Flarna** [comment]
It's not `dom` it's `es2017.sharedmemory` which is included in 3.1 typings via `/// <reference lib="es2018" />` but older typescript versions do not support the `reference lib` directive.
Forward declaration is used to avoid that need the everyone has to include it manually. Forward declarations shall be an `interface` as interfaces merge with classes whereas classes are not allowed to be defined twice. So using `class` for a forward declaration breaks builds where the lib with the real definition is included.

**Comment by SimonSchick** [comment]
@Flarna would simply adding `/// <reference lib="es2017.sharedmemory" />` to `/index.d.ts` work in this case?

**Comment by SimonSchick** [comment]
Also relevant since `Atomics` is still missing from those typings 🤔

**Comment by Flarna** [comment]
Nope as `/// <reference lib` has been introduced in typescript 3.0  and the effected file is that one which is used for 2.1...3.0.
@Mulperi Which typescript version do you use? I expect it's <3.1.

**Comment by jmeberlein** [comment]
I'm also getting this problem. And changing to a previous version of `@types/node` is not a feasible option, since `@types/connect` uses `*`, pulls `@^11.9`, and causes conflicts in the test suite.

**Comment by SimonSchick** [comment]
@Flarna I'm currently travelling, could you perhaps look into this?

**Comment by Flarna** [comment]
@jmeberlein Which typescript version do you use? I expect it's <3.1.

**Comment by Flarna** [comment]
created #33177. Hard to tell when this get's merged as CI is in a bad state currently.

**Comment by jmeberlein** [comment]
Typescript version ^2.9.2 in package.json, resolving to 2.9.2 in npm-shrinkwrap.json

**Comment by samuelt1** [comment]
why is this story closed? It seems to be broken still.

**Comment by wooliesx-apirillo** [comment]
> why is this story closed? It seems to be broken still.

This was resolved almost a year ago, so it seems it was fixed but has now regressed. I'd probably open a new issue.

**Comment by thameurr** [comment]
`ng] ERROR in node_modules/@types/node/index.d.ts:73:11 - error TS2300: Duplicate identifier 'IteratorResult'.
[ng] 73 interface IteratorResult<T> { }
[ng]              ~~~~~~~~~~~~~~
[ng]   node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
[ng]     41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
[ng]             ~~~~~~~~~~~~~~
[ng]     'IteratorResult' was also declared here.
[ng] node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.
[ng] 41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
[ng]         ~~~~~~~~~~~~~~
[ng]   node_modules/@types/node/index.d.ts:73:11
[ng]     73 interface IteratorResult<T> { }
[ng]                  ~~~~~~~~~~~~~~
[ng]     'IteratorResult' was also declared here.`

Problem still not resolved

**Comment by Flarna** [comment]
@thameurr Please note that you comment on an issue closed quite a while ago. I assume you use a different set of @types/node, typescript,... versions then that ones mentined in this issue.

Could you create a new issue with instructions how to reproduced where up to date versions of the packages are used?

**Comment by grantis** [comment]
I got this problem with `@types/node: "13.9.5"` and it was fixed by rolling back to `"12.12.31"` 🤷‍♂️

**Comment by MarkLeMerise** [comment]
This issue was still occurring for me with TypeScript 4.0.2. Installing `@types/node` at version `14.6.0` seemed to make the errors go away when running `tsc --noEmit`.

**Comment by koshuang** [comment]
Got the same error. It's fixed when I add `"skipLibCheck": true` into `tsconfig.json`.

**Comment by andrevmatos** [comment]
`@types/node@16.11.6` is affected by this; I got the issue with `typescript@4.4.4` and yarn:
```sh
yarn run v1.22.17
$ .../project/node_modules/.bin/tsc
../node_modules/@types/node/buffer.d.ts:97:14 - error TS2661: Cannot export 'Buffer'. Only local declarations can be exported from a module.

97     export { Buffer };
                ~~~~~~

Found 1 error.
error Command failed with exit code 2
```

**Comment by jeremy-rifkin** [comment]
Sorry to necrobump: I'm running into this same issue with node 20.14 and typescript 5.4.5.

```
node_modules/@types/node/events.d.ts(519,30): error TS2300: Duplicate identifier 'EventEmitter'.
node_modules/@types/node/stream.d.ts(53,11): error TS2420: Class 'ReadableBase' incorrectly implements interface 'ReadableStream'.
  Type 'ReadableBase' is missing the following properties from type 'ReadableStream': off, removeAllListeners, setMaxListeners, getMaxListeners, and 4 more.
node_modules/@types/node/stream.d.ts(662,11): error TS2420: Class 'WritableBase' incorrectly implements interface 'WritableStream'.
  Type 'WritableBase' is missing the following properties from type 'WritableStream': off, removeAllListeners, setMaxListeners, getMaxListeners, and 4 more.
node_modules/@types/node/test.d.ts(380,11): error TS2420: Class 'TestsStream' incorrectly implements interface 'ReadableStream'.
  Type 'TestsStream' is missing the following properties from type 'ReadableStream': off, removeAllListeners, setMaxListeners, getMaxListeners, and 4 more.
```
