### ISSUE TITLE
@types/reactstrap missing UncontrolledCollapse

### ISSUE THREAD

**Issue by efc** [DefinitelyTyped/DefinitelyTyped#26529]
Sorry, I don't know how to fix problems with @types, but I did notice that reactstrap 6.1.0 fixed a bug with UncontrolledCollapse, which had been missing until a few days ago, and @types/reactstrap 5.0.27 does not have a corresponding UncontrolledCollapse definition.

- I tried using the `@types/reactstrap` package and had problems with UncontrolledCollapse.
- Authors: @alihammad, @mfal, @danilobjr, @FaithForHumans, @KurtPreston, @timc13, @patrickrgaffney

**Comment by plat123456789** [comment]
same problem here

**Comment by JProff** [comment]
UncontrolledCarousel missing too

**Comment by seansfkelley** [comment]
Maintainers: this was fixed in #28638.

**Comment by AkivaRanells** [comment]
"UncontrolledCarousel" is still not imported/exported in type definitions @types\reactstrap\index.d.ts

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
