### ISSUE TITLE
StyledComponents, cannot ref

### ISSUE THREAD

**Issue by lukepighetti** [DefinitelyTyped/DefinitelyTyped#30451]
I seem to be unable to ref Styled Components with Typescript. I have asked another user about this and they believe this is a bug so I have decided to file an issue.

```
private _ref = React.createRef<HTMLDivElement>();

<SliderContainer
  ref={this._ref}
/>
```

```
const SliderContainer = styled.div`
  /* whatever */
`
```

<img width="808" alt="screen_shot_2018-11-11_at_5 44 35_pm" src="https://user-images.githubusercontent.com/666539/48319287-0687e280-e5da-11e8-9572-5800b646f30d.png">

Action: make a `styled.div` and ref it with `React.createRef<HTMLDivElement>()`
Expected behavior: it works
Actual behavior: type error

**Comment by lukepighetti** [comment]
https://github.com/styled-components/styled-components/issues/2202

**Comment by just-boris** [comment]
Should be fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30511
I installed the latest version and it worked fine for me.

**Comment by leoyli** [comment]
Nope, I still get this error when using the latest version.  Can someone testify this too?

**Comment by leoyli** [comment]
Okay, I have tested it is due to `{...props}` being placed at the last place, probably need something like  `Omit<React.ComponentProps<'img'>, 'ref'>` 🤔...  If I move it upfront, then the type error disappeared.

**Comment by ldanet** [comment]
Just passing props for `div`s (or `input`s or anything else for that matter) results in a Typescript error because of `ref`.

https://codesandbox.io/s/styled-components-ref-typescript-error-9hs8t

```ts
const StyledFoo = styled.div`
  color: red;
`;

const Foo = (props: JSX.IntrinsicElements['div']) => {
  return <StyledFoo {...props} />;
};
```

Line 12 there is the error on `<StyledFoo {...props} />`: 
```
Type '{ ref?: LegacyRef<HTMLDivElement>; key?: Key; defaultChecked?: boolean; defaultValue?: string | string[]; suppressContentEditableWarning?: boolean; suppressHydrationWarning?: boolean; accessKey?: string; ... 247 more ...; onTransitionEndCapture?: (event: TransitionEvent<...>) => void; }' is not assignable to type 'Pick<Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style" | "title" | "children" | "key" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 246 more ... | "onTransitionEndCapture"> & { ...; }, "style" | ... 253 more ... | "onTransitionEndCapture"> & Partial<....'.
  Types of property 'ref' are incompatible.
    Type 'LegacyRef<HTMLDivElement>' is not assignable to type '((instance: HTMLDivElement) => void) | RefObject<HTMLDivElement>'.
      Type 'string' is not assignable to type '((instance: HTMLDivElement) => void) | RefObject<HTMLDivElement>'.ts(2322)
```

**Comment by jsarge11** [comment]
Any updates on this? Still running into this error as well.

**Comment by szyman** [comment]
it looks I fixed when using this type assertion
`const ref = React.useRef() as React.MutableRefObject<HTMLInputElement>`

**Comment by caasi** [comment]
Is this a duplicate issue (#28884)?

**Comment by szyman** [comment]
This is related to `forwardRef`. This one seems to be duplicated https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35572

**Comment by 21lucasmessias** [comment]
This solve my problem:

index.tsx
`
...
const refInput = useRef<TextInput | null>(null);
...
<TextArea refer={refInput} />
`
styles.ts
`
import { TextInput } from 'react-native';
import styled from 'styled-components/native';

interface iTextInput {
  refer?: string | ((instance: TextInput | null) => void) | React.RefObject<TextInput> | null | undefined
}

export const TextLine = styled(TextInput).attrs<iTextInput>(
  ({ refer }) => ({
    ref: refer
  })
) <iTextInput>``
`

Tell me if this help

**Comment by jordyvandomselaar** [comment]
@szyman that's because the issue is that styled-components doesn't expect a `MutableRefObject` with value `undefined`. By type casting it, you're telling TypeScript the ref will always contain a HTML element. This _could_ lead to issues.

How I solved it:


```
  const ref = useRef<HTMLDivElement>(null);
```

By specifying `null`  as the default value, it works without errors.

**Comment by Tim-Pet** [comment]
Towards anyone stumbling upon this issue I was able to fix it utilising forward ref within the styled call. This way you can point the ref directly towards the inner component and not the styled wrapper. (in my case utilising React native btw)


```js
  <StyledInput
    ref={inputRef}
  />
  // ...

 const StyledInput = styled(
  forwardRef<TextInput, TextInputProps>((props, ref) => <TextInput {...props} ref={ref} />)
)`
  flex: 2;
  margin-left: 10px;
  color: ${({ theme }) => theme.colors.fc.primary};
  ${({ theme }) => theme.typography.copyLarge};
`;

          
```

Also @jordyvandomselaar comment is necessary to be stop TS complaining.

Furthermore, if you want to expose the refs via imperative handle you can default it back to undefined instead of null. 
e.g.:

```js
 useImperativeHandle(ref, () => ({
      setInputProps: (props) => {
        inputRef.current?.setNativeProps(props);
      },
      blur() {
        inputRef.current?.blur();
      },
      get input() {
        return inputRef.current ?? undefined;
      },
      get searchField() {
        return searchFieldRef.current ?? undefined;
      },
    }));
```
