### ISSUE TITLE
[@types/react] 16.8.5 breaks assignability of components that use Pick, Exclude, generics and/or conditional types

### ISSUE THREAD

**Issue by NiGhTTraX** [DefinitelyTyped/DefinitelyTyped#33461]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @VincentLanglet @threepointone @pshrmn @johnnyreilly @bbenezech @onigoetz @theruther4d

Example code: https://github.com/NiGhTTraX/react-connect-state/blob/132c3a8e8ad880f79078127ce149758d5c324804/src/connect.tsx#L29 that works in `16.8.4`. I apologize for not providing a simpler example but I tried reducing it and couldn't reproduce so I'm not sure which part of my code is causing this. I have manually reverted the commit below and my code compiles again.

```
Error:(29, 15) TS2322: Type 'Readonly<PropsWithChildren<Pick<ViewProps, Exclude<keyof ViewProps, K>>>>' is not assignable to type 'IntrinsicAttributes & Pick<ViewProps, Exclude<keyof ViewProps, K>> & { children?: ReactNode; }'.
  Type 'Readonly<PropsWithChildren<Pick<ViewProps, Exclude<keyof ViewProps, K>>>>' is not assignable to type 'Pick<ViewProps, Exclude<keyof ViewProps, K>>'.
    Type 'PropsWithChildren<Pick<ViewProps, Exclude<keyof ViewProps, K>>>[P]' is not assignable to type 'ViewProps[P]'.
      Type 'PropsWithChildren<Pick<ViewProps, Exclude<keyof ViewProps, K>>>' is not assignable to type 'ViewProps'.
```

Caused by https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b5200f6fb7cccddadd4d17870aa53b8b5bd1198d#diff-96b72df8b13a8a590e4f160cbc51f40c. I don't understand why though, maybe the way `Readonly` distributes over the new type?

**Comment by VincentLanglet** [comment]
Thanks !
I suspected something here : https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33416
This is maybe related to https://github.com/Microsoft/TypeScript/issues/28339

I am going to take a look today

**Comment by VincentLanglet** [comment]
This PR should fix the problem :  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33462
Seems like `Readonly<A> & Readonly<B> != Readonly<A & B>`

**Comment by NiGhTTraX** [comment]
Thanks @VincentLanglet!

**Comment by arthur-chan-leapyear** [comment]
Hmm, I am still getting this in the latest, `16.8.22`. It works fine in `16.8.4`.

It is kind of important so that you don't have to write boilerplate everywhere, for example you can make a GraphQL component shortcut like:

```
import { Mutation, MutationFn, MutationResult, MutationProps } from 'react-apollo'
import { DocumentNode } from 'graphql'

export type MutationComponentProps<TData, TVariables = {}> = Pick<
  MutationProps<TData, TVariables>,
  Exclude<keyof MutationProps<TData, TVariables>, 'mutation'>
>

export function createMutationComponent<TData, TVariables = {}>(
  MUTATION: DocumentNode
): FC<MutationComponentProps<TData, TVariables>> {
  class MutationComponent extends Mutation<TData, TVariables> {}
  return ({ children, ...props }) => (
    <MutationComponent
      mutation={MUTATION}
      {...props as JSX.LibraryManagedAttributes<MutationComponentProps<TData, TVariables>, typeof Mutation>}>
      {(mutationFn: MutationFn<TData, TVariables>, result: MutationResult<TData>) => children(mutationFn, result)}
    </MutationComponent>
  )
}
```

and then in some other file do something like

```
// index.ts with createMutationComponent example
import { createMutationComponent, MutationRenderProps } from '@api/utils'
import { login, loginVariables } from './login'
import LOGIN_MUTATION from './login.graphql'

export const LoginMutation = createMutationComponent<login, loginVariables>(LOGIN_MUTATION)
export { LOGIN_MUTATION, login, loginVariables }
export type LoginMutationRenderProps = MutationRenderProps<login, loginVariables>
```

```
# login.graphql
mutation login($name: String!, $password: String!) {
  login(data: { name: $name, password: $password })
}
```

```
// login.ts
/* tslint:disable */
/* eslint-disable */
// This file was automatically generated and should not be edited.

// ====================================================
// GraphQL mutation operation: login
// ====================================================

export interface login {
  login: string;
}

export interface loginVariables {
  name: string;
  password: string;
}
```
