### ISSUE TITLE
[@types/lodash] Property 'map' does not exist on type FunctionChain<any>

### ISSUE THREAD

**Issue by EugeneDraitsev** [DefinitelyTyped/DefinitelyTyped#35625]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aj-r @sandersn
 
One more similar to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35400 issue (ts is in strick mode):

```jsx
chain([1, 2, 3, 4, 5])
  .reduce((acc: any, x) => {
    acc[x] = x
    return acc
  }, {})
  .map(x => x * 2)
  .value()
```

with `@types/lodash` **4.14.121** it works fine, but with **4.14.126** I get a type error:
```
 Property 'map' does not exist on type 'FunctionChain<any> | ObjectChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | CollectionChain<...>'.
  Property 'map' does not exist on type 'FunctionChain<any>'.
```

Obviously `map` function is exist here in any case and this is incorrect error. 

**Update**: Same issue happens with `mapValues` after reduce too

**Comment by aj-r** [comment]
I think the types are having trouble with the `acc: any` part. It might be possible to fix but I'm not sure.

You can probably give a stricter type than `any`, e.g. `(acc: { [key: string]: any }, x) => ...`. That should fix the error, and has the added benefit of being more type-safe.

**Comment by EugeneDraitsev** [comment]
@aj-r, you're right it will work as expected with more strict type:
```jsx
interface MyInterface { [key: string]: any }

chain([1, 2, 3, 4, 5])
  .reduce((acc: MyInterface, x) => {
    acc[x] = x
    return acc
  }, {} as MyInterface)
  .map(x => x * 2)
  .value()
```

But error 
```
 Property 'map' does not exist on type 'FunctionChain<any> | ObjectChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | CollectionChain<...>'.
  Property 'map' does not exist on type 'FunctionChain<any>'.
```

still doesn't make any sense. In case of `acc: any` you still have property `map` on your `FunctionChain<any>`. At least this is incorrect error message.

**Comment by sandersn** [comment]
The problem is that `reduce` returns `acc`, and when `acc: any`, it can't guarantee that it **does** have the `map` method. It might be a function, for example, which doesn't have `map`. You should either add a type to `acc` or not put a type annotation at all (which is a noImplicitAny error, but fine without strict on).

**Comment by EugeneDraitsev** [comment]
You're right `acc` might be a string, number or function, but `map` always exists at `Chain<any>`:

```jsx
const { chain } = require('lodash')

const fn = chain([1, 2, 3, 4, 5])
  .reduce(() => () => {})

const num = chain([1, 2, 3, 4, 5])
  .reduce(() => 42)

const str = chain([1, 2, 3, 4, 5])
  .reduce(() => 'string')


console.log(fn.map) // [Function]
console.log(num.map) // [Function]
console.log(str.map) // [Function]
```

So maybe semantically this error make sense, but this error get wrong information to end users

**Comment by EugeneDraitsev** [comment]
@aj-r @sandersn, any updates about that? If my points are not enough here, so here is 1 more unsolvable point:

```tsx
interface Token {
  [key: string]: any
}

chain(decodedToken as Token).get('[cognito:groups]').map(decodeGroup).orderBy().value()
```
```
Property 'map' does not exist on type 'FunctionChain<any> | ObjectChain<any> | PrimitiveChain<any> | StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | StringNullableChain | CollectionChain<...>'.
  Property 'map' does not exist on type 'FunctionChain<any>'.
```

There is no any way to fix that, except ugly any-wrapper:
```tsx
(chain(decodedToken as Token).get('[cognito:groups]') as any).map(decodeGroup).orderBy().value()
```

`map`, `mapValues` and `get` should exist at ObjectChain<any> | PrimitiveChain<any>. Otherwise meaning of `any` has no any sense here.

**Comment by yesterdaytime** [comment]
I use the lodash(4.17.11) and the different @types/lodash(4.14.118 and 4.14.136), the 4.14.118 is worked, but the 4.14.136 is showing the error.

**Comment by rgehan** [comment]
It is still happening with v4.14.149

**Comment by alvarezr** [comment]
where you guys able to figured out this issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by natoszme** [comment]
hi guys! do you know where i can follow this issue on Discussions?
thanks!
