### ISSUE TITLE
[@types/validator] Circular definition of import alias 'Validator'.

### ISSUE THREAD

**Issue by esetnik** [DefinitelyTyped/DefinitelyTyped#40477]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MunifTanjim @samuelneff @CodeAnimal @drinchev @babolivier @kukoo1 @oktapodia @MorpheusXAUT @TitaneBoy @zjy01 @nidzov @Raigen @todd @nrschultz @Thomas-B @Antoine38660 @smff @truongkhanhduy95 @emmanuelgautier @dancrumb @lalayueh @rohitsud @Torhal @tgfjt @chrootsu @IOAyman @louy @kacepe @deptno @builtinnya @qqilihq @keatz55

Example:
```ts
import validator from 'validator';
```

```
5:11:26 PM: ERROR in /opt/build/repo/node_modules/@types/validator/index.d.ts
5:11:26 PM: ERROR in /opt/build/repo/node_modules/@types/validator/index.d.ts(1247,8):
5:11:26 PM: TS2303: Circular definition of import alias 'Validator'.
```

It is caused by the release of @types/validator@12.0.0 (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40192)

**Comment by topwood** [comment]
mark

**Comment by topwood** [comment]
node_modules/_@types_sequelize@4.27.47@@types/sequelize/index.d.ts:6296:33 - error TS2503: Cannot find namespace 'ValidatorJS'.

**Comment by oktapodia** [comment]
Related to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40192#issuecomment-555203904

**Comment by louy** [comment]
@topwood are you using an older version of sequelize types? I think that might be your issue, which is different to the other one

I’ll try to take a look later today. Strange how CI didn’t catch that circular reference

**Comment by topwood** [comment]
In my package.json

"sequelize": "^4.43.1",
"sequelize-typescript": "^0.6.9"

How to slove this? @louy

**Comment by topwood** [comment]
![image](https://user-images.githubusercontent.com/13791267/69144197-b8b78b80-0b05-11ea-98c2-09ea39a19e3a.png)

**Comment by louy** [comment]
@topwood Can you try updating both packages to the latest?

    npm i -S @types/sequelize@latest @types/validator@latest

**Comment by topwood** [comment]
It still do not work for me..sad

**Comment by louy** [comment]
@topwood yeah actually updating to the latest should give you the same issue as above

> TS2303: Circular definition of import alias 'Validator'.

I have a fix in #40491

**Comment by EduardsE** [comment]
@louy is there any way to circumvent this until we wait for this to get merged?

**Comment by louy** [comment]
You can try using an older version of the types package

**Comment by EduardsE** [comment]
> You can try using an older version of the types package

Is this possible if `validator` is a dependency of a dependency? In my case sequelize is using `validator`.

**Comment by EduardsE** [comment]
Ok, downgrading `@types/sequelize` from `4.28.8` to `4.28.1` solved my issue.

**Comment by Jeontaeyun** [comment]
i have same problem with 
`@types/sequelize@4.28.1` and `@sequelize-typescript 1.0.0`
how can i solve this problem?

**Comment by asmsuechan** [comment]
Have the same error. I downgraded `@types/sequelize` to the previous version `10.11.3` and my `tsc` is working fine now.

ref: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40192#issuecomment-555203904

**Comment by cjancsar** [comment]
@asmsuechan `@types/sequelize` latest version is `4.28.7`, do you mean you downgraded to `4.28.6`, or are you talking about a different lib?

**Comment by malord** [comment]
As a temporary workaround, installing both @types/sequelize@4.28.1 and @types/validator@10.11.3 worked for my project.

**Comment by louy** [comment]
`@types/validator@12.0.1` should now solve this problem

**Comment by muyu66** [comment]
> `@types/validator@12.0.1` should now solve this problem

From my practice, **@types/validator@12.0.1**  cannot solve this problem.
my package.json is
`
"sequelize": "^5.21.3",
"@types/validator": "^12.0.1",
`
I still have this error (Cannot find namespace 'ValidatorJS')

My solution was to remove the **@types/validator** package
`
npm remove @types/validator
`
Don't need to use it explicitly after all
