### ISSUE TITLE
Outdated types on mui-datatables

### ISSUE THREAD

**Issue by hugobarragon** [DefinitelyTyped/DefinitelyTyped#45909]
Missing alot of types on [mui-datatables](https://www.npmjs.com/package/mui-datatables?activeTab=readme) package

https://github.com/gregnb/mui-datatables#options
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mui-datatables/index.d.ts#L162
for example : `confirmFilters` and `customFilterDialogFooter ` and the table state to with `sortOrder`

MUIDataTableState missing options versus normal tableState
![image](https://user-images.githubusercontent.com/35630927/86590422-7ef99f00-bf87-11ea-9f6f-ffe0544681c1.png)

Definitions by: Jeroen "Favna" Claassens @Favna  <https://github.com/favna>
//                 Ankith Konda @ankithkonda  <https://github.com/ankithkonda>
//                 Herman "Von" Waters IV @hwatersiv  <https://github.com/hwatersiv>
//                 souppower @souppower  <https://github.com/souppower>
//                 Byron "Byrekt" Mitchell @byrekt  <https://github.com/byrekt>

**Comment by Favna** [comment]
If the maintainers of this repo would ever merge my PR they would get added https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45306

**Comment by hugobarragon** [comment]
> If the maintainers of this repo would ever merge my PR they would get added #45306
> 
> But despite asking for it multiple times on Gitter and mentioning them on the PR they are completely non-responsive.

Now that we have and issue maybe it goes through, nice one man, thanks for the PR, I didnt know there was one already 👍 lets see what happens. 👀

**Comment by peterblazejewicz** [comment]
fixed in #45306

**Comment by hugobarragon** [comment]
@peterblazejewicz already updated, but on  `MUIDataTableState ` sort order still missing
```
export interface MUIDataTableState {
    activeColumn: string | null;
    announceText: string | null;
    columns: MUIDataTableColumnState[];
    count: number;
    data: any[];
    displayData: Array<{ dataIndex: number; data: any[] }>;
    expandedRows: MUIDataTableStateRows;
    filterData: any[];
    filterList: string[][];
    page: number;
    rowsPerPage: number;
    rowsPerPageOptions: number[];
    searchText: string | null;
    selectedRows: MUIDataTableStateRows;
    showResponsive: boolean;
}
```

**Comment by Favna** [comment]
Oh I see what the core of the problem is here, those properties are on `MUIDataTableOptions` but not `MUIDataTableState`. The reason for this is because I followed the migration documentation and the README doesn't properly document the type of the table state.

From the migration guide:

> # sortDirection deprecated in favor of sortOrder
> The sort direction of the table is now controlled by options.sortOrder (example). Using a sortDirection value on a column's options object will still work, but it will print a >? > deprecation notice when run in development mode.
> 
> More information here: gregnb/mui-datatables/pull/1310


Can you create a pull request to add these types? At least that way I'll approve it (once all good of course) and as the bot will automate the process then it won't be another month before your changes will land.

**Comment by hugobarragon** [comment]
PR here #45981
