### ISSUE TITLE
[@types/google-apps-script] CardService is missing methods

### ISSUE THREAD

**Issue by kvernon** [DefinitelyTyped/DefinitelyTyped#46898]
Recently I've been trying to add a footer, if you try to do the suggested cat tutorial idea: https://developers.google.com/gsuite/add-ons/cats-quickstart, it cannot find `setFixedFooter()`

area of concern:
```
...

// Create a footer to be shown at the bottom.
  var footer = CardService.newFixedFooter()
      .setPrimaryButton(CardService.newTextButton()
          .setText('Powered by cataas.com')
          .setOpenLink(CardService.newOpenLink()
              .setUrl('https://cataas.com')));

  // Assemble the widgets and return the card.
  var section = CardService.newCardSection()
      .addWidget(image)
      .addWidget(buttonSet);
  var card = CardService.newCardBuilder()
      .addSection(section)
      .setDisplayStyle(DisplayStyle.REPLACE) // cannot find setDisplayStyle and DisplayStyle enum
      .setFixedFooter(footer); // cannot find
...

```

note: on version:     "@types/google-apps-script": "^1.0.14"

@PopGoesTheWza , @grant

**Comment by simeyla** [comment]
`newDecoratedText` is also missing

**Comment by PopGoesTheWza** [comment]
@kvernon @simeyla is this issue still current? Quite a few PRs have been merged recently.

**Comment by simeyla** [comment]
@PopGoesTheWza I'm jumping around projects and not actively working with AppsScript right now, but just updated to 1.0.27 and newDecoratedText() is now present so I was able to update my code. I haven't actually executed it yet but I'm assuming it'll work. I don't see any `<any>` anywhere else in my code so looks like I'm good :-)

**Comment by mtgto** [comment]
Fixed in #51952.

**Comment by cxa-croper** [comment]
The DisplayStyle enum is still missing from CardService, so this isn't _quite_ fixed.
