### ISSUE TITLE
[@types/express-session] Breaking change under patch release

### ISSUE THREAD

**Issue by rijkvanzanten** [DefinitelyTyped/DefinitelyTyped#49484]
- [x] I tried using the `@types/express-session` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jacobbogers, @builtinnya, @Ry7n, @fiznool, @peterblazejewicz, @HoldYourWaffle

---

When updating from `1.17.0` to `1.17.1` of `@types/express-session`, I was suddenly greeted by TS errors whenever I use things like `req.session.customProperty = customValue;`. AFAIK, this is still valid usage of `express-session` (see the `req.session.views` example at https://www.npmjs.com/package/express-session#reqsession) and shouldn't throw an error.

I noticed a little example in the source code of how to inject your own properties "properly" into the `express-session` SessionData namespace:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/43028c1b80b5ffed47d61b4694e53059a87ce2d8/types/express-session/index.d.ts#L204-L217

But this is a breaking change and should've been released as a major instead of a patch release.

Should we update

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/43028c1b80b5ffed47d61b4694e53059a87ce2d8/types/express-session/index.d.ts#L216-L217

to

```ts
    interface SessionData {
        [key: string]: any;
    }
```

so it's not a breaking change?

**Comment by rijkvanzanten** [comment]
This particular change has been fixed in #49479. However, that PR it itself is another breaking change in a patch.... I believe we should leave this open to discuss what the meaning of the version numbers is under the `@types/express-session` package 👀

**Comment by andrewbranch** [comment]
Answered here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49479#issuecomment-726896690

**Comment by mopcweb** [comment]
Please, reopen, issue is not resolved yet!
This changes also breaks connect-redis, as it uses under the hood express-session declarations!
Please, revert all changes to be same as there were before

**Comment by HoldYourWaffle** [comment]
@mopcweb Please keep in mind that the breaking changes in #46576 (excluding the `InitializedSession`) were necessary, because the previous definitions were simply incorrect (as described in #46576).

**Comment by mopcweb** [comment]
@HoldYourWaffle i believe you.

But i think it is incorrect that a bunch of projects which used it without any changes in dependencies are broken.
In my case the fix was by strictly passing "@types/express-session" "1.17.0" in dependencies section in yarn.lock, which i think is not correct (

**Comment by HoldYourWaffle** [comment]
> But i think it is incorrect that a bunch of projects which used it without any changes in dependencies are broken.

Although I agree that this is very annoying, this is a natural consequence of the way NPM handles dependencies combined with DT not doing SemVer ([for good reason](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49479#issuecomment-726896690)).
You can prevent this (as you said) by locking down the version in your lockfile, although as far as I know you can also do this in `package.json`.

**Comment by mopcweb** [comment]
@HoldYourWaffle Thanks for your explanation and suggestions! I'll try `skipLibCheck` a bit later.
