### ISSUE TITLE
[@types/async] - clarification before I make a PR

### ISSUE THREAD

**Issue by Brice1994** [DefinitelyTyped/DefinitelyTyped#50347]
-Authors
@borisyankov
@kern0
@Penryn
@fenying
@pascalmartin
@Dmitri1337
@erossignon
@Juliiii
@brendtumi

According to the documentation at https://caolan.github.io/async/v3/docs.html#some, it looks like all of the collection methods return a promise if no callback is provided, there's some exports in the index.d.ts like filter:

`export function filter<T, E = Error>(arr: IterableCollection<T>, iterator: AsyncBooleanIterator<T, E>, callback: AsyncResultArrayCallback<T, E>): void;`

`export function filter<T, E = Error>(arr: IterableCollection<T>, iterator: AsyncBooleanIterator<T, E>): Promise<T[]>;`

that are typed to return a Promise if no callback is provided, but there are others such as 'some' that only have the void declaration: 

`export function some<T, E = Error>(arr: IterableCollection<T>, iterator: AsyncBooleanIterator<T, E>, callback?: AsyncBooleanResultCallback<E>): void;`

Was this intentional? I'd like the use the code like this:

`const found = await find(collection, async (v) =>(await  v.foo()) == "something")`

But typescript complains that found is void.

I can make a PR but I just want to make sure this wasn't intentional for some reason, considering there's a lot of consumers of this library and I couldn't find anything related.

**Comment by zbjornson** [comment]
You're correct, many of the promisified methods are missing and/or wrong. I'm slowly working on them, starting with #51540.

**Comment by Brice1994** [comment]
Resolved in: [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51540](url)

**Comment by ThePletch** [comment]
@Brice1994 Closed incorrectly - linked PR addressed only one function. Several still do not have type definitions for their promise-based equivalents, e.g. `some`

**Comment by ThePletch** [comment]
whoops sorry you're not a maintainer, close your own issue at your leisure 😬
