### ISSUE TITLE
[@types/pdfmake] Type 'string' is not assignable to type 'Alignment'

### ISSUE THREAD

**Issue by HeCorr** [DefinitelyTyped/DefinitelyTyped#51554]
Hello. I'm having the error `Type 'string' is not assignable to type 'Alignment'.` when using `alignment: 'center'`.

Same error happens with `margin: [20, 0, 0, 0]`: `Type 'number[]' is not assignable to type '[number, number, number, number]'.`

Even if I have this **very** simple document:
```ts
var pdfDoc = {
    content:[
        {
            margin: [0,0,0,0],
            table: {
                body: [[
                    'nope'
                ]]
            },
        }
    ]
}

printer.createPdfKitDocument(pdfDoc)
```

<details>
<summary>Full error message</summary>

```
Argument of type '{ content: { margin: number[]; table: { body: string[][]; }; }[]; }' is not assignable to parameter of type 'TDocumentDefinitions'.
  Types of property 'content' are incompatible.
    Type '{ margin: number[]; table: { body: string[][]; }; }[]' is not assignable to type 'Content'.
      Type '{ margin: number[]; table: { body: string[][]; }; }[]' is not assignable to type 'ArrayOfContent'.
        The types returned by 'pop()' are incompatible between these types.
          Type '{ margin: number[]; table: { body: string[][]; }; }' is not assignable to type 'Content'.
            Type '{ margin: number[]; table: { body: string[][]; }; }' is not assignable to type 'ContentTable'.
              Types of property 'margin' are incompatible.
                Type 'number[]' is not assignable to type 'Margins'.
                  Type 'number[]' is not assignable to type '[number, number, number, number]'.
                    Target requires 4 element(s) but source may have fewer.
```

</details>

I couldn't find literally anyone else with the same issue so I have no idea of what's causing it or how to fix it.

Versions:
TypeScript `4.2.2`
pdfmake `0.1.70`
@types/pdfmake `0.1.16`

@m1llen1um / @radziksh / @evolkmann / @andipaetzold / @nmummau / @jeralm

**Comment by andipaetzold** [comment]
Hey @HeCorr ,

the issue is that `'nope'` automatically infers the type `string` and `[20, 0, 0, 0]` automatically infers the type `number[]`.

Using `as const` should resolve the issue as it makes `'nope'` infer the type `'nope'` and `[20, 0, 0, 0]` infer the type `[number, number, number, number]`

See the TypeScript docs: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions

Your example with `as const`:
```
var pdfDoc = {
    content:[
        {
            margin: [0,0,0,0],
            table: {
                body: [[
                    'nope'
                ]]
            },
        }
    ]
} as const

printer.createPdfKitDocument(pdfDoc)
```

**Comment by HeCorr** [comment]
Thank you for the quick response, Andi!

Unfortunately it didn't solve the issue as I am now getting this error:

```
Argument of type '{ readonly content: readonly [{ readonly margin: readonly [0, 0, 0, 0]; readonly table: { readonly body: readonly [readonly ["nope"]]; }; }]; }' is not assignable to parameter of type 'TDocumentDefinitions'.
  Types of property 'content' are incompatible.
    Type 'readonly [{ readonly margin: readonly [0, 0, 0, 0]; readonly table: { readonly body: readonly [readonly ["nope"]]; }; }]' is not assignable to type 'Content'.
      Type 'readonly [{ readonly margin: readonly [0, 0, 0, 0]; readonly table: { readonly body: readonly [readonly ["nope"]]; }; }]' is not assignable to type 'ArrayOfContent'.
```

**Comment by andipaetzold** [comment]
Hmm true, ran into the same issue myself once.

How about `as TDocumentDefinition`. On my machine, this resolved your issue. This solution looks as if it would skip type checking by casting the type but typescript is actually still checking the compatibility of the object before assigning the new type.

```typescript
var pdfDoc = {
  content: [
    {
      margin: [0, 0, 0, 0],
      table: {
        body: [["nope"]],
      },
    },
  ],
} as TDocumentDefinitions;
```

**Comment by HeCorr** [comment]
Oh.. I haven't thought of trying that, hahah! I'm still a TypeScript beginner after all  :)

Indeed it does solve my issue, thank you very much!

**Comment by HeCorr** [comment]
A recommendation for whoever encounters the same issue, as per my observations:

Instead of using `as TDocumentDefinitions` at the end of a variable, it is preferable to use the standart TypeScript variable type definition: `var pdfDoc:TDocumentDefinitions` as that will also enable error checking and intellisense for embedded variable objects, like in this example:

```ts
var pdfContent: Content = {
    // if there was a typo here, you wouldn't notice if using 'as TDocumentDefinitions' at the end of pdfDoc.
    { text: 'this method is safer' } 
}

var pdfDoc: TDocumentDefinitions = {
    content: pdfContent
}
```

**Comment by jeralm** [comment]
> A recommendation for whoever encounters the same issue, as per my observations:
> 
> Instead of using `as TDocumentDefinitions` at the end of a variable, it is preferable to use the standart TypeScript variable type definition: `var pdfDoc:TDocumentDefinitions` as that will also enable error checking and intellisense for embedded variable objects, like in this example:
> 
> ```ts
> var pdfContent: Content = {
>     // if there was a typo here, you wouldn't notice if using 'as TDocumentDefinitions' at the end of pdfDoc.
>     { text: 'this method is safer' } 
> }
> 
> var pdfDoc: TDocumentDefinitions = {
>     content: pdfContent
> }
> ```

I second this. `as` (not `as const`!!) is usually dangerous and a bit fuzzy. What your appraoch does is it **disables type inference** for the variable `pdfContent`. Type inference usually works very well, but sometimes the information it retains is too much (can be argued about `as const`) or too little (your initial problem, without `as const`).

In this use-case, what you really want to know is if your content object is valid, but then, to process it, you only really need to know that it is a `Content`.
